#!/bin/sh
set -e
cd "$(dirname "$0")/.."
changelog_dir=_CHANGELOGS
changelog_ext=md
default_changelog=$(cat <<EOF
# Changelog
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](http://keepachangelog.com/en/1.0.0/)
and this project adheres to [Semantic Versioning](http://semver.org/spec/v2.0.0.html).

EOF
)
if [ -n "$(find "$changelog_dir" -type f -name "*.$changelog_ext" 2>/dev/null)" ]; then
  if [ -f CHANGELOG.md ]; then
    pos=$(sed -rn '/^## /{=;q}' CHANGELOG.md)
  else
    echo "$default_changelog" > CHANGELOG.md
    git add CHANGELOG.md
    pos=
  fi
  [ -n "$pos" ] || pos=$(($(wc -l CHANGELOG.md) + 1))
  next_ver=$(poetry version -s)
  newchlog=$(mktemp)
  (
    head -n$((pos - 1)) CHANGELOG.md
    echo "## $next_ver"
    for category in Fixed Changed Added Removed; do
      logs=$(find "$changelog_dir/$category" -type f -name "*.$changelog_ext" 2>/dev/null|sort)
      if [ -n "$logs" ]; then
        echo "### $category"
        for log in $logs; do
          printf '%s' '- '
          cat "$log"
          tail -c1 "$log" | grep -q '^$' || echo ""
          git rm "$log" >/dev/null 2>&1
        done
      fi
    done
    echo ''
    tail -n+$pos CHANGELOG.md
  ) > "$newchlog"
  mv "$newchlog" CHANGELOG.md
  git add CHANGELOG.md
fi
