# Generated by Django 5.2.6 on 2025-12-05 12:50
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('oauth2_authcodeflow', '0005_alter_blacklistedtoken'),
    ]
    operations = [
        migrations.AlterField(
            model_name='blacklistedtoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
